- docs/documentos/Eps/Modelo_de_Elicitacao_de_Requisitos.md
Elaborei um documento modelo para elicitacao de requisitos do projeto, bem como a forma de documentar epicos, features e historias.
> added modelo_de_elicitacao_de_requisitos.md is29

- docs/documentos/Eps/Termo_de_abertura_do_Projeto.md
Fix #3 
Concluído o termo de abertura do projeto!
> Is3 termo de abertura de projeto tap

- leito_hospitalar/requirements.txt
Atualizei os requirements, adicionei o rest framework
> Update requirements rest framework

- docker-compose.yml
- requirements.txt
Instalação de dependências de micro serviço.
> Addition of micro service

- .travis.yml
Implementei a adaptação do deploy contínuo pelo travis!
> Adaptando travis para deploy continuo

- src/pages/HomePage.jsx
- src/pages/UpdateSchedule.jsx
Correção das informações do site.
> Refactoring of minor data

- docs/documentos/Mds/Documento_de_Visao.md
> Fix the doc with new scope

- docs/documentos/Mds/Documento_de_Visao.md
> Is01 elaborar doc de visao

- docs/documentos/Eps/EVM.md
Versao inicial do documento EVM para a primeira release.
> Is81 elaborar evm

- docs/documentos/Eps/Documento_GCS.md
Fiz algumas modificações no documento, atualizei as ferramentas utilizadas e descrevi o tópico que estava faltando.
> Update GCS version 0.2

- src/pages/DoctorStatus.jsx
Correção do bug que quebrava a pagina de alterar status.
> Change status bug fix

- .codeclimate.yml
- schedule/periods.py
- schedule/views.py
Mudança do nivel de qualidade do code climate.
> Code refactoring and codeclimate file new configuration

- src/css/ScheduleTable.css
- src/css/popup.css
- src/pages/ScheduleTable.jsx
Refatoramento do popup da tabela de horários
> Is135 melhorar popout

- docs/documentos/Eps/Documento_GCS.md
Retirei tecnologias que não vamos usar e adicionei as de monitoramento que já implementei.
> Update doc GCS

- src/pages/ScheduleTable.jsx
> Implementing Fetch on the popup

- docs/documentos/Sprints/Sprint_8_Planejamento.md
- docs/documentos/Sprints/Sprint_8_Resultados.md
Verificar posteriormente se as imagens estão carregando conforme o esperado.
> Is165 resultado sprint 8

- .travis.yml
Encriptei a chave do deploy para melhorar a segurança da aplicação.
> Update key deploy

- src/components/SideBar.jsx
- src/css/ScheduleTable.css
- src/pages/ScheduleTable.jsx
Criação e formatação da escala clínica.
> Is181 melhorar formataçao da tabela de horarios clinica

- src/components/PrivateRouter.js
- src/components/store.js
- src/pages/DoctorForm.jsx
- src/pages/DoctorStatus.jsx
- src/pages/LoginPage.jsx
Resolução dos warnings atuais do frontend.
> Is230 refatoraçao de codigo no frontend

- src/components/PrivateRouter.js
Arrumando um erro no private router
> Private Router Bug Fix

- docs/documentos/Eps/Detalhamento_de_Riscos.md
- docs/documentos/Eps/Gerenciamento_de_Riscos.md
- docs/documentos/Eps/registro_de_ocorrencia_de_riscos.md
Pull request relacionado ao registro de riscos que ocorreram durantes as sprints e as ações tomadas.
> Is219 atualizar riscos

- src/components/Modal.jsx
- src/css/bootstrap.css
Arrumando bug no modal do calendário onde não carregava o formulário de atualização de evento
> arrumando bug no modal

- src/components/FormDoctorForm.jsx
- src/components/Modal.jsx
- src/components/ModalForm.jsx
- src/pages/ScheduleTable.jsx
Funcionalidade de cadastro de novo evento de médicos pelo quadro horário.
> Is253 cadastrar medico pela tabela

- requirements.txt
- schedule/models/events.py
- schedule/urls.py
- schedule/views.py
- src/components/ModalForm.jsx
- src/pages/ScheduleTable.jsx
- tests/test_views.py
Integração do micro serviço de gerar pdf do quadro de horários mensal
> PDF Microservice integration

- schedule/urls.py
- schedule/views.py
- src/pages/ScheduleTable.jsx
Signed-off-by: Caio Beleza <caio.almeidabeleza@gmail.com>
Signed-off-by: ulyssesBML <ulysses3353@gmail.com>
Signed-off-by: joaosilva <joaovitordmrosa@hotmail.com>
Co-authored-by: ulyssesBML <ulysses3353@gmail.com>
Co-authored-by: joaosilva <joaovitordmrosa@hotmail.com>
> Adding generate xlsx button

- src/components/Workload.jsx
- src/pages/ScheduleTable.jsx
Signed-off-by: joaosilva <joaovitordmrosa@hotmail.com>
Signed-off-by: Caiocbeleza <caio.almeidabeleza@gmail.com>
Co-authored-by: Caiocbeleza <caio.almeidabeleza@gmail.com>
Co-authored-by: joaosilva <joaovitordmrosa@hotmail.com>
> Created Workload component.

- src/components/Form.jsx
- src/components/FormDoctorForm.jsx
- src/components/FormUpdate.jsx
- src/css/DoctorForm.css
- src/pages/LoginPage.jsx
- src/pages/RegistrationAdmin.jsx
Consertado os bugs com os formulários de erro e de redirecionamento das páginas.
> Is113 reparar bugs

- src/pages/ScheduleTable.jsx
Idioma do caléndario ajustado plenamente para pt-br.
> Changing laguage definitions

- src/components/Footer.js
- src/css/404Page.css
- src/css/DoctorForm.css
- src/css/HomePage.css
- src/css/NavBar.css
- src/css/bootstrap.css
- src/css/footer.css
- src/pages/HomePage.jsx
- src/pages/LoginPage.jsx
- src/pages/RegistrationAdmin.jsx
- src/pages/ScheduleTable.jsx
> Frontend adjustments

- schedule/urls.py
- schedule/views.py
- src/components/Modal.jsx
- src/pages/ScheduleTable.jsx
Adicionando a função real de deletar.
> Is297 deletar evento
